import type { ReactNode } from "react";
// Page-specific font subsets generated by scripts/generate-fonts.ts — NOT the
// @fontsource CSS, whose ~240 unicode-range @font-face rules added ~290 KB to
// this render-blocking stylesheet.
import "../generated/fonts.css";
import "../styles.css";

export default async function RootLayout({ children }: { children: ReactNode }) {
  return <>{children}</>;
}

export const getConfig = async () => {
  return { render: "static" } as const;
};
