// Generates optimized avatar variants at build time with sharp. The source
// public/avatar.png (460x460, ~230 KB) stays in the repo as the master copy
// (generate-og.ts embeds it at 220px into the OG image), but serving it for
// the 96px-displayed profile picture wasted ~220 KB per visit.
//
// The page variant is a 192px (2x DPR) webp emitted as a data URI module
// rather than a file: at ~4.4 KB it is the LCP element, and inlining it into
// the HTML removes the image fetch round trip from the LCP critical path
// entirely (LCP then coincides with first paint). The favicon stays a real
// file (a 96px png). Output is gitignored, like og.png.
//
// Runs directly with `node scripts/generate-images.ts` (type stripping), so
// only erasable TypeScript syntax is used.

import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import sharp from "sharp";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const source = join(root, "public/avatar.png");

const webp = await sharp(source).resize(192, 192).webp({ quality: 82 }).toBuffer();
mkdirSync(join(root, "src/generated"), { recursive: true });
writeFileSync(
  join(root, "src/generated/avatar.ts"),
  `// generated by scripts/generate-images.ts — do not edit\nexport const avatarSrc = "data:image/webp;base64,${webp.toString("base64")}";\n`,
);
console.log(`generated src/generated/avatar.ts (${webp.length} bytes of webp)`);

const icon = await sharp(source).resize(96, 96).png().toFile(join(root, "public/avatar-96.png"));
console.log(`generated public/avatar-96.png (${icon.size} bytes)`);
