// Generates page-specific font subsets at build time with subset-font
// (harfbuzz). The @fontsource CSS this replaces declares ~240 @font-face
// rules (every unicode-range slice of every weight), which alone made the
// render-blocking stylesheet ~290 KB; the woff2 slices it points at also
// can't be preloaded sensibly because which slices the browser fetches
// depends on unicode-range matching at layout time.
//
// Instead, this script collects every character that can appear on the page
// and produces exactly two woff2 files (400/700) containing only those
// glyphs, plus a two-rule @font-face stylesheet and a TS module listing the
// files so _root.tsx can <link rel="preload"> them.
//
// Characters are collected by scanning whole source files (src/pages,
// src/components, src/lib) rather than extracting string literals: this is
// over-inclusive (code and comments add a handful of glyphs) but can never
// miss rendered text, so editing links.ts never requires touching this
// script. Printable ASCII is always included as a floor.
//
// The subset source is @fontsource's monolithic "japanese" file, which
// contains the full glyph set (including basic latin) — see the same note in
// generate-og.ts. Nothing is committed and no network access is needed:
// output goes to public/fonts/ and src/generated/ (both gitignored).
//
// Runs directly with `node scripts/generate-fonts.ts` (type stripping), so
// only erasable TypeScript syntax is used.

import { createHash } from "node:crypto";
import { mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import subsetFont from "subset-font";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");

const chars = new Set<string>();
for (let c = 0x20; c <= 0x7e; c++) chars.add(String.fromCharCode(c));
for (const dir of ["src/pages", "src/components", "src/lib"]) {
  for (const file of readdirSync(join(root, dir))) {
    if (!/\.tsx?$/.test(file)) continue;
    for (const ch of readFileSync(join(root, dir, file), "utf8")) chars.add(ch);
  }
}
const text = [...chars].join("");

const fontDir = join(root, "node_modules/@fontsource/m-plus-rounded-1c/files");
const outDir = join(root, "public/fonts");
rmSync(outDir, { recursive: true, force: true });
mkdirSync(outDir, { recursive: true });

const weights = [400, 700] as const;
const urls: string[] = [];
for (const weight of weights) {
  const source = readFileSync(join(fontDir, `m-plus-rounded-1c-japanese-${weight}-normal.woff`));
  const woff2 = await subsetFont(source, text, { targetFormat: "woff2" });
  const hash = createHash("sha256").update(woff2).digest("hex").slice(0, 8);
  const name = `m-plus-rounded-1c-${weight}.${hash}.woff2`;
  writeFileSync(join(outDir, name), woff2);
  urls.push(`/fonts/${name}`);
  console.log(`generated public/fonts/${name} (${woff2.length} bytes)`);
}

const banner = "generated by scripts/generate-fonts.ts — do not edit";

const css = urls
  .map(
    (url, i) => `@font-face {
  font-family: "M PLUS Rounded 1c";
  font-style: normal;
  font-display: swap;
  font-weight: ${weights[i]};
  src: url("${url}") format("woff2");
}`,
  )
  .join("\n");
mkdirSync(join(root, "src/generated"), { recursive: true });
writeFileSync(join(root, "src/generated/fonts.css"), `/* ${banner} */\n${css}\n`);

writeFileSync(
  join(root, "src/generated/fonts.ts"),
  `// ${banner}\nexport const fontPreloads: readonly string[] = ${JSON.stringify(urls)};\n`,
);
console.log("generated src/generated/fonts.{css,ts}");
